# Generated by Django 5.0.2 on 2026-01-06 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='item',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='item',
            name='highest_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.buyer'),
        ),
        migrations.AddField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('COMING_SOON', 'Coming soon'), ('LIVE', 'Live'), ('ENDED', 'Ended')], default='COMING_SOON', max_length=20),
        ),
    ]
